# Generated by Django 3.1.5 on 2021-08-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210802_1123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image_link',
            new_name='image_link1',
        ),
        migrations.AddField(
            model_name='product',
            name='image_link2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='image_link3',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='image_link4',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
