# Generated by Django 3.2.4 on 2021-08-04 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_newsletter_image_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='newsletter',
            name='main_news',
            field=models.BooleanField(default=False),
        ),
    ]
